### ISSUE TITLE
Link showing all existing pads

### ISSUE THREAD

**Issue by samcro1967** [JustKato/FreePad#14]
Is there any link to show all pads that have been created with a link to each?  Any maybe a delete button for each one?

**Comment by JustKato** [comment]
The easiest way for you to admin this at the moment is simply looking in the data folder, if you are using docker mount the volume as shown in the example docker file and all of the pads will pop in that folder where you'll be able to manually delete them.
All pads are actual files on the disk, so, changing them or deleting them will have the same effect as an admin interface.
The above is a solution to your problem for this second.
I am planning on adding an admin interface similar to psitransfer's, where you will get ALL pads listed, their expiery date, their last modified and views along with the action for deletion.

**Comment by JustKato** [comment]
A new branch was added for this issue, I'll try and get it done in about a day or two.
Thanks for the feedback!

**Comment by JustKato** [comment]
Quick update, the feature has been implemented, you can access the admin via `/admin/login` then you will be prompted for the password that can be set in the `.env` with the key `ADMIN_TOKEN`
I've just not had enough time to work on this to be as polished as I wanted it to be, so I will keep it as a separate branch for one more day, most probably this saturday I will get to finishing this.
Thanks for waiting :)

**Comment by samcro1967** [comment]
I pulled the branch and have it running.  I can get to /admin/login and successfully enter my password.  After that I am taken back to the main page.  Is there a link to view all pads?  Might also want to add a version in the footer of the main page so it is easy to identify what version you are running.

**Comment by JustKato** [comment]
Is that so? That is extremely weird.
You are supposed to be redirected to `/admin/view`, please make sure that the admin token is properly set when running, you only get redirected if and only if you have the wrong cookie set

**Comment by JustKato** [comment]
Try and access `/admin/view` and see if you are being redirected, check your browser's storage for cookies and check if you do have a cookie.
If the environment value for `ADMIN_TOKEN` is empty then the admin interface is turned completely off

**Comment by samcro1967** [comment]
I am running with the docker-compose below.  Image was built with `docker build -t freepad_admin https://github.com/JustKato/FreePad.git#feature/password-protection`.  /admin/view redirects me back to the main page.
```
  freepad:
    hostname: freepad
    image: freepad_admin
    container_name: freepad
    restart: always
    ports:
      - 3113:8080
    environment:
      - DOMAIN_BASE=http://osu.freepad:3113
      - CACHE_MAP_LIMIT=15
      - PAD_STORAGE_PATH=./data/
      - API_BAN_LIMIT=300
      - DEV_MODE=0
      - CLEANUP_MAX_AGE=43200 #1 month
      - MAXIMUM_PAD_SIZE= 1048576 # 1mb
      - GIN_MODE=release
      - ADMIN_TOKEN=$PASSWORD
```
